app/models.py
from flask_login import UserMixin
from flask_sqlalchemy import SQLAlchemy
from sqlalchemy.schema import Column
from sqlalchemy.types import Integer, String
from werkzeug.security import generate_password_hash, check_password_hash

db = SQLAlchemy()


class Employee(UserMixin, db.Model):
    __tablename__ = "employees"
    id = Column(Integer, primary_key=True)
    name = Column(String(100), nullable=False)
    employee_number = Column(Integer, unique=True, nullable=False)
    hashed_password = Column(String(255), nullable=False)

    @property
    def password(self):
        return self.hashed_password

    @password.setter
    def password(self, password):
        self.hashed_password = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password, password)

app/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField
from wtforms.validators import DataRequired


class LoginForm(FlaskForm):
    employee_number = StringField("Employee Number", validators=[DataRequired()])
    password = PasswordField("Password", validators=[DataRequired()])
    submit = SubmitField("Submit")

app/__init__.py
from flask import Flask
from flask_login import LoginManager
from .config import Configuration
from .models import db, Employee
from .routes import orders, session

app = Flask(__name__)
app.config.from_object(Configuration)
app.register_blueprint(orders.bp)
app.register_blueprint(session.bp)
db.init_app(app)

login = LoginManager(app)
login.login_view = "session.login"


@login.user_loader
def load_user(id):
    return Employee.query.get(int(id))

app/routes/orders.py
from flask import Blueprint, render_template
from flask_login import login_required

bp = Blueprint("orders", __name__, url_prefix="")


@bp.route("/")
@login_required
def index():
    return render_template("orders.html")

app/routes/session.py
from flask import Blueprint, render_template, redirect, url_for
from flask_login import current_user, login_user, logout_user
from ..models import Employee
from ..forms import LoginForm

bp = Blueprint("session", __name__, url_prefix="/session")


@bp.route("/", methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        return redirect(url_for("orders.index"))
    form = LoginForm()
    if form.validate_on_submit():
        empl_number = form.employee_number.data
        employee = Employee.query.filter(
            Employee.employee_number == empl_number
        ).first()
        if not employee or not employee.check_password(form.password.data):
            return redirect(url_for("orders.index"))
        login_user(employee)
        return redirect(url_for("orders.index"))
    return render_template("login.html", form=form)


@bp.route("/logout", methods=["POST"])
def logout():
    logout_user()
    return redirect(url_for(".login"))

app/templates/base.html
<html>

<head>
    {% if title %}
    <title>{{ title }} - Order Up!</title>
    {% else %}
    <title>Welcome to Order Up!</title>
    {% endif %}
</head>

<body>
    {% block content %}
    {% endblock %}

    {% if not current_user.is_anonymous %}
    <form method="POST" action="{{ url_for('session.logout') }}">
        <button type="submit">Logout</button>
    </form>
    {% endif %}
</body>

</html>

app/templates/login.html
{% extends "base.html" %}

{% block content %}
<form method="POST" action="{{ url_for('.login') }}">
    {{ form.hidden_tag() }}
    {{ form.csrf_token }}
    <div>
        {{ form.employee_number.label }} {{ form.employee_number }}

        {% if form.employee_number.errors %}
        <ul>
            {% for error in form.employee_number.errors %}
            <li>{{ error }}</li>
            {% endfor %}
        </ul>
        {% endif %}
    </div>
    <div>
        {{ form.password.label }} {{ form.password }}

        {% if form.password.errors %}
        <ul>
            {% for error in form.password.errors %}
            <li>{{ error }}</li>
            {% endfor %}
        </ul>
        {% endif %}
    </div>
    <div>{{ form.submit }}</div>
</form>
{% endblock %}

app/templates/orders.html
{% extends "base.html" %}

{% block content %}
<h1>Order Up!</h1>
{% endblock %}